#ifndef COMPILER_DEFINITIONSTATET_H_
#define COMPILER_DEFINITIONSTATET_H_

typedef char definitionState_t;

enum {
	DEFINITIONSTATE_UNDEFINED,
	DEFINITIONSTATE_READING,
	DEFINITIONSTATE_DONE,
	DEFINITIONSTATE_NOEXIST,
};

#endif